apiVersion: v1
kind: Secret
metadata:
  name: toklabel
  namespace: label-studio
type: Opaque
stringData:
  # Label Studio Configuration
  label-studio-url: "http://<LABEL_STUDIO_HOST>:<LABEL_STUDIO_PORT>/"
  label-studio-api-key: "<YOUR_API_KEY>"
  
  # Redis Configuration
  redis-password: "<REDIS_PASSWORD>"
  
  # ML Backend URLs
  ip-features-model-url: "http://<LABEL_STUDIO_HOST>:<LABEL_STUDIO_PORT>/ml-models-ip-features/"
  discharge-timing-model-url: "http://<LABEL_STUDIO_HOST>:<LABEL_STUDIO_PORT>/ml-models-discharge-timing-features/"
  
  # Database Configuration
  postgres-username: "<DB_USER>"
  postgres-password: "<DB_PASSWORD>"
  
  # Label Studio Enterprise License (if applicable)
  enterprise-license: "<YOUR_LICENSE_KEY>" 